const threeBldCornerPairs = {
  AA: "-",
  AB: "-",
  AC: "-",
  AD: "-",
  AE: "-",
  AF: "-",
  AG: "-",
  AH: "-",
  AI: "-",
  AJ: "-",
  AK: "-",
  AL: "-",
  AM: "-",
  AN: "-",
  AO: "-",
  AP: "-",
  AQ: "-",
  AR: "-",
  AS: "-",
  AT: "-",
  AU: "-",
  AV: "-",
  AW: "-",
  AX: "-",
  BA: "-",
  BB: "-",
  BC: "burning crusade",
  BD: "bande dessinée",
  BE: "beuh",
  BF: "beaufort",
  BG: "bague",
  BH: "bâche",
  BI: "bi",
  BJ: "-",
  BK: "burger king",
  BL: "bleu",
  BM: "-",
  BN: "-",
  BO: "bonbon",
  BP: "bip",
  BQ: "-",
  BR: "battle rez",
  BS: "bullshit",
  BT: "beuteu",
  BU: "b.u.",
  BV: "bave",
  BW: "boue",
  BX: "biche",
  CA: "-",
  CB: "carte bleue",
  CC: "-",
  CD: "c.d.",
  CE: "c.e.",
  CF: "-",
  CG: "segway",
  CH: "chat",
  CI: "-",
  CJ: "cajou",
  CK: "cake",
  CL: "clac",
  CM: "camion",
  CN: "-",
  CO: "coq",
  CP: "cèpe",
  CQ: "-",
  CR: "croc",
  CS: "counter strike",
  CT: "cute",
  CU: "cul",
  CV: "curriculum",
  CW: "couette",
  CX: "sachet",
  DA: "-",
  DB: "database",
  DC: "déco",
  DD: "-",
  DE: "-",
  DF: "défoncé",
  DG: "dague",
  DH: "Direct hit",
  DI: "discord",
  DJ: "dj",
  DK: "donkey kong",
  DL: "download",
  DM: "demo",
  DN: "-",
  DO: "dodo",
  DP: "dep",
  DQ: "-",
  DR: "-",
  DS: "ds",
  DT: "date",
  DU: "dur",
  DV: "d.va",
  DW: "doux",
  DX: "douche",
  EA: "-",
  EB: "eh beh",
  EC: "essai",
  ED: "-",
  EE: "-",
  EF: "f",
  EG: "exemple",
  EH: "-",
  EI: "oeil",
  EJ: "egypte",
  EK: "ethereal knives",
  EL: "élément",
  EM: "émetteur",
  EN: "-",
  EO: "éolienne",
  EP: "episode",
  EQ: "-",
  ER: "-",
  ES: "espagne",
  ET: "E.T.",
  EU: "europe",
  EV: "evolution",
  EW: "eww",
  EX: "échange",
  FA: "-",
  FB: "facebook",
  FC: "-",
  FD: "fada",
  FE: "feu",
  FF: "-",
  FG: "forum gold",
  FH: "first hit",
  FI: "-",
  FJ: "feuj",
  FK: "féculent",
  FL: "fil",
  FM: "femme",
  FN: "-",
  FO: "faux",
  FP: "fap",
  FQ: "-",
  FR: "france",
  FS: "fesse",
  FT: "fête",
  FU: "fût",
  FV: "fève",
  FW: "fouet",
  FX: "faucheuse",
  GA: "-",
  GB: "grande bretagne",
  GC: "grand charme",
  GD: "gheed",
  GE: "gueu",
  GF: "gf18",
  GG: "-",
  GH: "-",
  GI: "g.i",
  GJ: "garage",
  GK: "geek",
  GL: "-",
  GM: "grand master",
  GN: "-",
  GO: "go",
  GP: "gp explorer",
  GQ: "-",
  GR: "gros",
  GS: "gearscore",
  GT: "gt gabi",
  GU: "-",
  GV: "-",
  GW: "gouine",
  GX: "gauche",
  HA: "-",
  HB: "happy birthday",
  HC: "hardcore",
  HD: "hd",
  HE: "H.E.",
  HF: "haut fait",
  HG: "hug",
  HH: "-",
  HI: "hi",
  HJ: "high jump",
  HK: "hong kong",
  HL: "haut lvl",
  HM: "25hm",
  HN: "-",
  HO: "-",
  HP: "-",
  HQ: "-",
  HR: "high rune",
  HS: "-",
  HT: "-",
  HU: "-",
  HV: "hotel ventes",
  HW: "ah ouais",
  HX: "hache",
  IA: "-",
  IB: "hibou",
  IC: "-",
  ID: "idée",
  IE: "interro écrite",
  IF: "-",
  IG: "instagram",
  IH: "-",
  II: "-",
  IJ: "-",
  IK: "immortal king",
  IL: "ile",
  IM: "-",
  IN: "-",
  IO: "in/out",
  IP: "i.p.",
  IQ: "-",
  IR: "infrarouge",
  IS: "isis",
  IT: "i.t.",
  IU: "-",
  IV: "-",
  IW: "-",
  IX: "ich ich",
  JA: "-",
  JB: "-",
  JC: "jesus christ",
  JD: "jd",
  JE: "jean emmanuel",
  JF: "jofre",
  JG: "jogging",
  JH: "-",
  JI: "-",
  JJ: "-",
  JK: "joke",
  JL: "-",
  JM: "-",
  JN: "-",
  JO: "jeux olympiques",
  JP: "jeep",
  JQ: "-",
  JR: "-",
  JS: "javascript",
  JT: "j.t.",
  JU: "jus",
  JV: "-",
  JW: "jehova",
  JX: "-",
  KA: "-",
  KB: "knockback",
  KC: "cascade",
  KD: "cadeau",
  KE: "-",
  KF: "café",
  KG: "cage",
  KH: "carhartt",
  KI: "kiki",
  KJ: "kanji",
  KK: "-",
  KL: "klaxon",
  KM: "kimono",
  KN: "-",
  KO: "k.o.",
  KP: "-",
  KQ: "-",
  KR: "car",
  KS: "killstreak",
  KT: "kitkat",
  KU: "cul",
  KV: "kevlar",
  KW: "-",
  KX: "couche",
  LA: "-",
  LB: "lobe",
  LC: "lacet",
  LD: "led",
  LE: "-",
  LF: "-",
  LG: "-",
  LH: "-",
  LI: "lit",
  LJ: "liège",
  LK: "lich king",
  LL: "-",
  LM: "lame",
  LN: "-",
  LO: "lolo",
  LP: "lip",
  LQ: "-",
  LR: "lore",
  LS: "laisse",
  LT: "leet",
  LU: "petit lu",
  LV: "-",
  LW: "loup",
  LX: "louche",
  MA: "-",
  MB: "-",
  MC: "mc solaar",
  MD: "mdma",
  ME: "-",
  MF: "motherfucker",
  MG: "mug",
  MH: "maphack",
  MI: "mii",
  MJ: "-",
  MK: "molkky",
  ML: "machine learning",
  MM: "-",
  MN: "-",
  MO: "mmo",
  MP: "mep",
  MQ: "-",
  MR: "mer",
  MS: "miss",
  MT: "mite",
  MU: "mue",
  MV: "move",
  MW: "mouette",
  MX: "mx518",
  NA: "-",
  NB: "-",
  NC: "-",
  ND: "-",
  NE: "-",
  NF: "-",
  NG: "-",
  NH: "-",
  NI: "-",
  NJ: "-",
  NK: "-",
  NL: "-",
  NM: "-",
  NN: "-",
  NO: "-",
  NP: "-",
  NQ: "-",
  NR: "-",
  NS: "-",
  NT: "-",
  NU: "-",
  NV: "-",
  NW: "-",
  NX: "-",
  OA: "-",
  OB: "obélix",
  OC: "océan",
  OD: "overdose",
  OE: "oeuf",
  OF: "onlyfans",
  OG: "original gangster",
  OH: "one handed",
  OI: "oi (pirate)",
  OJ: "orange juice",
  OK: "ok",
  OL: "olympique l",
  OM: "olympique m",
  ON: "-",
  OO: "-",
  OP: "op",
  OQ: "-",
  OR: "or",
  OS: "os",
  OT: "-",
  OU: "houx",
  OV: "ovni",
  OW: "overwatch",
  OX: "-",
  PA: "-",
  PB: "personal best",
  PC: "pc",
  PD: "pd",
  PE: "peut être",
  PF: "pouf",
  PG: "pog",
  PH: "ph neutre",
  PI: "pi",
  PJ: "pyjama",
  PK: "-",
  PL: "pile",
  PM: "p.m.",
  PN: "-",
  PO: "pot",
  PP: "-",
  PQ: "-",
  PR: "père",
  PS: "p.s.",
  PT: "pété",
  PU: "-",
  PV: "point de vie",
  PW: "-",
  PX: "pêche",
  QA: "-",
  QB: "-",
  QC: "-",
  QD: "-",
  QE: "-",
  QF: "-",
  QG: "-",
  QH: "-",
  QI: "-",
  QJ: "-",
  QK: "-",
  QL: "-",
  QM: "-",
  QN: "-",
  QO: "-",
  QP: "-",
  QQ: "-",
  QR: "-",
  QS: "-",
  QT: "-",
  QU: "-",
  QV: "-",
  QW: "-",
  QX: "-",
  RA: "-",
  RB: "rubis",
  RC: "release candidate",
  RD: "-",
  RE: "-",
  RF: "renfo",
  RG: "rogue",
  RH: "r.h.",
  RI: "riz",
  RJ: "rage",
  RK: "rikiki",
  RL: "reel",
  RM: "-",
  RN: "-",
  RO: "ragnarok online",
  RP: "roleplay",
  RQ: "-",
  RR: "-",
  RS: "russe",
  RT: "roti",
  RU: "r.u.",
  RV: "rave",
  RW: "roux",
  RX: "ruche",
  SA: "-",
  SB: "sbire",
  SC: "starcraft",
  SD: "carte SD",
  SE: "-",
  SF: "science fiction",
  SG: "saggy",
  SH: "-",
  SI: "-",
  SJ: "sage",
  SK: "souk",
  SL: "solo",
  SM: "sado-maso",
  SN: "-",
  SO: "sud ouest",
  SP: "soupe",
  SQ: "-",
  SR: "souris",
  SS: "-",
  ST: "-",
  SU: "-",
  SV: "serveur",
  SW: "sous",
  SX: "souche",
  TA: "-",
  TB: "très bien",
  TC: "télécom",
  TD: "t.d.",
  TE: "-",
  TF: "teuf",
  TG: "ta gueule",
  TH: "-",
  TI: "tee",
  TJ: "-",
  TK: "taekwondo",
  TL: "telephone",
  TM: "-",
  TN: "-",
  TO: "-",
  TP: "téléport",
  TQ: "-",
  TR: "terre",
  TS: "teamspeak",
  TT: "-",
  TU: "tutu",
  TV: "television",
  TW: "toux",
  TX: "-",
  UA: "-",
  UB: "-",
  UC: "-",
  UD: "-",
  UE: "-",
  UF: "-",
  UG: "-",
  UH: "-",
  UI: "huitre",
  UJ: "-",
  UK: "united kingdom",
  UL: "ulysse",
  UM: "-",
  UN: "-",
  UO: "-",
  UP: "up",
  UQ: "-",
  UR: "urêtre",
  US: "-",
  UT: "hutte",
  UU: "-",
  UV: "u.v.",
  UW: "uwu",
  UX: "ux ui",
  VA: "-",
  VB: "vibe",
  VC: "vessie",
  VD: "vador",
  VE: "voeu",
  VF: "voix fr",
  VG: "-",
  VH: "-",
  VI: "vie",
  VJ: "veja",
  VK: "vekna",
  VL: "-",
  VM: "vm linux",
  VN: "-",
  VO: "veau",
  VP: "vip",
  VQ: "-",
  VR: "v.r.",
  VS: "versus",
  VT: "vtt",
  VU: "vu",
  VV: "-",
  VW: "volkswagen",
  VX: "vache",
  WA: "-",
  WB: "web",
  WC: "wc",
  WD: "weed",
  WE: "weekend",
  WF: "windforce",
  WG: "wagon",
  WH: "wallhack",
  WI: "wii",
  WJ: "weirdjump",
  WK: "-",
  WL: "wailord",
  WM: "wam",
  WN: "-",
  WO: "wow",
  WP: "-",
  WQ: "-",
  WR: "wario",
  WS: "west",
  WT: "what",
  WU: "wut",
  WV: "wave",
  WW: "-",
  WX: "wesh",
  XA: "-",
  XB: "chibre",
  XC: "chausson",
  XD: "mdr",
  XE: "cheveu",
  XF: "chef",
  XG: "chug",
  XH: "-",
  XI: "chien",
  XJ: "choji",
  XK: "sheik",
  XL: "x.l.",
  XM: "chemin",
  XN: "-",
  XO: "-",
  XP: "choppe",
  XQ: "-",
  XR: "x.r.",
  XS: "chasse",
  XT: "chatte",
  XU: "-",
  XV: "-",
  XW: "-",
  XX: "-",
};

const pllCases = [
  {
    name: "Aa",
    sides: [
      ["A", "A", "C"],
      ["D", "B", "A"],
      ["B", "C", "B"],
      ["C", "D", "D"],
    ],
  },
  {
    name: "Ab",
    sides: [
      ["A", "A", "B"],
      ["C", "B", "C"],
      ["D", "C", "A"],
      ["B", "D", "D"],
    ],
  },
  {
    name: "E",
    sides: [
      ["D", "A", "B"],
      ["C", "B", "A"],
      ["B", "C", "D"],
      ["A", "D", "C"],
    ],
  },
  {
    name: "F",
    sides: [
      ["A", "C", "B"],
      ["C", "B", "A"],
      ["B", "A", "C"],
      ["D", "D", "D"],
    ],
  },
  {
    name: "Ga",
    sides: [
      ["A", "B", "B"],
      ["C", "D", "A"],
      ["B", "A", "C"],
      ["D", "C", "D"],
    ],
  },
  {
    name: "Gb",
    sides: [
      ["A", "C", "B"],
      ["C", "A", "A"],
      ["B", "D", "C"],
      ["D", "B", "D"],
    ],
  },
  {
    name: "Gc",
    sides: [
      ["A", "C", "B"],
      ["C", "D", "A"],
      ["B", "B", "C"],
      ["D", "A", "D"],
    ],
  },
  {
    name: "Gd",
    sides: [
      ["A", "D", "B"],
      ["C", "C", "A"],
      ["B", "A", "C"],
      ["D", "B", "D"],
    ],
  },
  {
    name: "H",
    sides: [
      ["A", "C", "A"],
      ["B", "D", "B"],
      ["C", "A", "C"],
      ["D", "B", "D"],
    ],
  },
  {
    name: "Ja",
    sides: [
      ["A", "A", "B"],
      ["C", "C", "A"],
      ["B", "B", "C"],
      ["D", "D", "D"],
    ],
  },
  {
    name: "Jb",
    sides: [
      ["D", "A", "A"],
      ["B", "D", "D"],
      ["A", "B", "B"],
      ["C", "C", "C"],
    ],
  },
  {
    name: "Na",
    sides: [
      ["C", "A", "A"],
      ["B", "D", "D"],
      ["A", "C", "C"],
      ["D", "B", "B"],
    ],
  },
  {
    name: "Nb",
    sides: [
      ["A", "A", "C"],
      ["D", "D", "B"],
      ["C", "C", "A"],
      ["B", "B", "D"],
    ],
  },
  {
    name: "Ra",
    sides: [
      ["D", "D", "A"],
      ["B", "A", "D"],
      ["A", "C", "B"],
      ["C", "B", "C"],
    ],
  },
  {
    name: "Rb",
    sides: [
      ["B", "A", "C"],
      ["D", "C", "B"],
      ["C", "D", "D"],
      ["A", "B", "A"],
    ],
  },
  {
    name: "T",
    sides: [
      ["A", "A", "B"],
      ["C", "D", "A"],
      ["B", "C", "C"],
      ["D", "B", "D"],
    ],
  },
  {
    name: "Ua",
    sides: [
      ["A", "B", "A"],
      ["B", "D", "B"],
      ["C", "C", "C"],
      ["D", "A", "D"],
    ],
  },
  {
    name: "Ub",
    sides: [
      ["A", "D", "A"],
      ["B", "A", "B"],
      ["C", "C", "C"],
      ["D", "B", "D"],
    ],
  },
  {
    name: "V",
    sides: [
      ["A", "A", "C"],
      ["D", "C", "B"],
      ["C", "B", "A"],
      ["B", "D", "D"],
    ],
  },
  {
    name: "Y",
    sides: [
      ["A", "A", "C"],
      ["D", "B", "B"],
      ["C", "D", "A"],
      ["B", "C", "D"],
    ],
  },
  {
    name: "Z",
    sides: [
      ["D", "C", "D"],
      ["A", "B", "A"],
      ["B", "A", "B"],
      ["C", "D", "C"],
    ],
  },
];

export { pllCases, threeBldCornerPairs };
