import type { Settings } from "@/composables/settings/types";
import trainingConstants from "./training";
const { pllCases, threeBldCornerPairs } = trainingConstants;

const defaultSettings: Settings = {
  theme: "bi",
  blindfoldedMode: false,
  timerFormat: "3decimals",
  blindfoldedTraining: {
    mode: "alternate",
    maximumRecognitionTime: 5,
    resultsViewMode: "key",
    threeBldCornerPairs,
  },
  pllRecognition: {
    pllPool: pllCases.map((pll) => pll.name),
  },
  letterScheme: {
    corners: {
      ULB: "B",
      UBR: "C",
      URF: "D",
      UFL: "A",
      LBU: "M",
      LUF: "N",
      LFD: "O",
      LDB: "P",
      FLU: "Q",
      FUR: "R",
      FRD: "S",
      FDL: "T",
      RFU: "E",
      RUB: "F",
      RBD: "G",
      RDF: "H",
      BRU: "I",
      BUL: "J",
      BLD: "K",
      BDR: "L",
      DLF: "X",
      DFR: "U",
      DRB: "V",
      DBL: "W",
    },
    edges: {
      UB: "B",
      UR: "C",
      UF: "D",
      UL: "A",
      LU: "M",
      LF: "N",
      LD: "O",
      LB: "P",
      FU: "Q",
      FR: "R",
      FD: "S",
      FL: "T",
      RU: "E",
      RB: "F",
      RD: "G",
      RF: "H",
      BU: "I",
      BL: "J",
      BD: "K",
      BR: "L",
      DF: "X",
      DR: "U",
      DB: "V",
      DL: "W",
    },
    centers: {
      U: "A",
      L: "M",
      F: "Q",
      R: "E",
      B: "I",
      D: "U",
    },
  },
};

export default {
  defaultSettings,
};
