import type { Settings } from "@/composables/settings/types";
import trainingConstants from "./training";
const { pllCases, threeBldCornerPairs } = trainingConstants;

const defaultSettings: Settings = {
  theme: "bi",
  blindfoldedMode: false,
  timerFormat: "3decimals",
  blindfoldedTraining: {
    mode: "alternate",
    maximumRecognitionTime: 5,
    resultsViewMode: "key",
    threeBldCornerPairs,
  },
  pllRecognition: {
    pllPool: pllCases.map((pll) => pll.name),
  },
  letterScheme: {
    corners: {
      ULB: "B",
      UBR: "C",
      URF: "D",
      UFL: "A",
      LBU: "M",
      LUF: "N",
      LFD: "O",
      LDB: "P",
      FLU: "Q",
      FUR: "R",
      FRD: "S",
      FDL: "T",
      RFU: "E",
      RUB: "F",
      RBD: "G",
      RDF: "H",
      BRU: "I",
      BUL: "J",
      BLD: "K",
      BDR: "L",
      DLF: "X",
      DFR: "U",
      DRB: "V",
      DBL: "W",
    },
    edges: {
      UB: "A",
      UR: "B",
      UF: "C",
      UL: "D",
      LU: "E",
      LF: "F",
      LD: "G",
      LB: "H",
      FU: "I",
      FR: "J",
      FD: "K",
      FL: "L",
      RU: "M",
      RB: "N",
      RD: "O",
      RF: "P",
      BU: "Q",
      BL: "R",
      BD: "S",
      BR: "T",
      DF: "U",
      DR: "V",
      DB: "W",
      DL: "X",
    },
    centers: {
      U: "A",
      L: "E",
      F: "I",
      R: "M",
      B: "Q",
      D: "U",
    },
  },
};

export default {
  defaultSettings,
};
