import type { Settings } from "@/composables/settings/types";
import trainingConstants from "./training";
const { pllCases, threeBldCornerPairs } = trainingConstants;

const defaultSettings: Settings = {
  theme: "bi",
  blindfoldedMode: false,
  timerFormat: "3decimals",
  blindfoldedTraining: {
    mode: "alternate",
    maximumRecognitionTime: 5,
    resultsViewMode: "key",
    threeBldCornerPairs,
  },
  pllRecognition: {
    pllPool: pllCases.map((pll) => pll.name),
  },
  blindfolded: {
    edgeBuffer: "B",
    cornerBuffer: "A",
    letterScheme: {
      corners: {
        ULB: "A",
        UBR: "B",
        URF: "C",
        UFL: "D",
        LBU: "E",
        LUF: "F",
        LFD: "G",
        LDB: "H",
        FLU: "I",
        FUR: "J",
        FRD: "K",
        FDL: "L",
        RFU: "M",
        RUB: "N",
        RBD: "O",
        RDF: "P",
        BRU: "Q",
        BUL: "R",
        BLD: "S",
        BDR: "T",
        DLF: "U",
        DFR: "V",
        DRB: "W",
        DBL: "X",
      },
      edges: {
        UB: "A",
        UR: "B",
        UF: "C",
        UL: "D",
        LU: "E",
        LF: "F",
        LD: "G",
        LB: "H",
        FU: "I",
        FR: "J",
        FD: "K",
        FL: "L",
        RU: "M",
        RB: "N",
        RD: "O",
        RF: "P",
        BU: "Q",
        BL: "R",
        BD: "S",
        BR: "T",
        DF: "U",
        DR: "V",
        DB: "W",
        DL: "X",
      },
      centers: {
        U: "A",
        L: "M",
        F: "Q",
        R: "E",
        B: "I",
        D: "U",
      },
    },
  },
};

export default {
  defaultSettings,
};
